load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "pool",
    srcs = ["pool.go"],
    importpath = "github.com/fughilli/hitl-reserve/pool",
    visibility = ["//visibility:public"],
    deps = ["//api"],
)

go_test(
    name = "pool_test",
    srcs = ["pool_test.go"],
    embed = [":pool"],
    deps = ["//api"],
)
