load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "engine",
    srcs = ["engine.go"],
    importpath = "github.com/fughilli/hitl-reserve/engine",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "//runner",
    ],
)

go_test(
    name = "engine_test",
    srcs = [
        "engine_test.go",
        "provision_test.go",
    ],
    embed = [":engine"],
    deps = [
        "//api",
        "//runner",
    ],
)
