load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "runner",
    srcs = [
        "podman.go",
        "runner.go",
        "usbport.go",
    ],
    importpath = "github.com/fughilli/hitl-reserve/runner",
    visibility = ["//visibility:public"],
    deps = ["//api"],
)

go_test(
    name = "runner_test",
    srcs = ["podman_test.go"],
    embed = [":runner"],
)
